### ISSUE TITLE
Delicious Safari stopped working on Mavericks

### ISSUE THREAD

**Issue by loucimj** [drichardson/DeliciousSafari#3]
Hi!, The UI looks as always, but it's not saving the bookmarks on delicious.

It doesn't report any issue.

Can you fix it?

It sucks to seek for another solution...and I payed a license because it's very useful!

Kind regards,
Javier

**Comment by drichardson** [comment]
I'm officially closing down this project, so this issue won't be fixed. [See  here](http://delicioussafari.com/) for more details.
